import { load } from "cheerio";
import { auditUrl } from "../audit/auditUrl";
import { inspectRepo } from "../repo/inspectRepo";
import { createSocialPreviewFromAudit } from "../socialPreview/socialPreview";
import {
  CONTRACT_NAMES,
  GeneratedSiteSmellsJsonContractSchema,
  type CliErrorCode,
  type GeneratedSiteSmellsJsonContract,
} from "../types/contracts";
import type { AuditResult } from "../types/audit";
import type { SocialPreviewJsonContract } from "../types/contracts";
import type { RepoInspectionResult } from "../types/repoInspection";
import { normalizeAuditUrl } from "../utils/url";
import {
  createMockGeneratedSiteSmells,
  parseGeneratedSiteSmellMockScenario,
} from "./mockGeneratedSiteSmells";
import {
  DEFAULT_GENERATED_SITE_SMELL_LIMITS,
  GeneratedSiteSmellsError,
  type GeneratedSiteSmellsInput,
  type GeneratedSiteSmellsResult,
} from "./generatedSiteSmellTypes";
import {
  assetExistsForPublicPath,
  findLineEvidence,
  hasRepoDirectory,
  hasRepoFile,
  isHtmlFile,
  isMetadataOrConfigPath,
  isSourceLikeFile,
  normalizeSmellScanLimits,
  sanitizeValuePreview,
  scanRepoForSmellInputs,
  type LineEvidence,
  type RepoSmellScan,
  type ScannedRepoFile,
} from "./repoSmellScanner";

type Finding = GeneratedSiteSmellsJsonContract["findings"][number];
type Evidence = Finding["evidence"][number];

type HtmlMetadata = {
  path: string;
  title?: string;
  description?: string;
  socialImages: Array<{ field: string; value: string; line?: number }>;
  favicons: Array<{ value: string; line?: number }>;
  hasOpenGraph: boolean;
};

const METADATA_SOURCE_PATTERN = /react-helmet|<Helmet\b|document\.title|og:title|twitter:title|twitter:image|og:image|meta\s+name=["']description|openGraph\s*:|metadata\s*=|export\s+const\s+metadata|generateMetadata/i;
const PLACEHOLDER_PATTERN = /\b(lorem ipsum|todo\b|fixme\b|change me|replace me|your (site|brand|company|title|description)|untitled|coming soon)\b/i;
const BOILERPLATE_PATTERN = /Vite \+ React|\/vite\.svg|\/react\.svg|Learn React|Edit src\/App|create-vite|create-next-app|Get started by editing|next\.svg|vercel\.svg/i;
const HARDCODED_URL_PATTERN = /https?:\/\/(?:localhost|127\.0\.0\.1|0\.0\.0\.0|example\.(?:com|org|net))(?::\d+)?[^\s"'<>)]*/i;
const GENERATED_MARKER_PATTERN = /@generated|auto-generated|automatically generated|do not edit|generated by/i;
const LOCAL_ASSET_PATTERN = /["'](\/(?!\/)[^"'\s)]+\.(?:png|jpe?g|webp|gif|svg|ico))([?#][^"']*)?["']/gi;

const CATEGORY_ORDER: GeneratedSiteSmellsJsonContract["findings"][number]["category"][] = [
  "metadata",
  "preview",
  "crawlability",
  "routing",
  "assets",
  "content_placeholders",
  "generated_boilerplate",
  "configuration",
  "framework",
  "unknown",
];

export async function getGeneratedSiteSmells(
  input: GeneratedSiteSmellsInput,
): Promise<GeneratedSiteSmellsResult> {
  const checkedAt = input.checkedAt ?? new Date().toISOString();
  const limits = normalizeSmellScanLimits({
    maxFiles: input.maxFiles,
    maxBytes: input.maxBytes,
  });
  const mock = parseGeneratedSiteSmellMockScenario(input.mock);
  const url = input.url ? normalizeSmellUrl(input.url) : undefined;

  let inspection: RepoInspectionResult;
  try {
    inspection = inspectRepo(input.repoPath, {
      cwd: input.cwd,
      maxFiles: Math.max(limits.maxFiles * 4, limits.maxFiles),
    });
  } catch (error) {
    const message = error instanceof Error ? error.message : "Repository path must be an existing accessible directory.";
    throw new GeneratedSiteSmellsError("invalid_repo_path", message);
  }

  if (mock) {
    return createMockGeneratedSiteSmells({
      scenario: mock,
      repoPath: inspection.path,
      url,
      framework: inspection.framework,
      limits,
    });
  }

  let scan: RepoSmellScan;
  try {
    scan = scanRepoForSmellInputs(input.repoPath, {
      cwd: input.cwd,
      limits,
    });
  } catch (error) {
    const message = error instanceof Error ? error.message : "Repository path must be an existing accessible directory.";
    throw new GeneratedSiteSmellsError("invalid_repo_path", message);
  }

  let audit: AuditResult | undefined;
  if (url) {
    audit = await auditUrl(url, {
      timeoutMs: input.timeoutMs,
      userAgent: input.userAgent,
      render: input.render,
    });
  }
  const socialPreview = audit
    ? createSocialPreviewFromAudit({
      audit,
      checkedAt: audit.auditedAt,
      mode: "live",
      sourceMode: "both",
      checkAssets: false,
    })
    : undefined;

  const findings = sortFindings(limitFindings([
    ...frameworkFindings(inspection, scan),
    ...crawlabilityFindings(inspection, scan),
    ...metadataFindings(inspection, scan, audit, socialPreview),
    ...placeholderFindings(scan),
    ...assetFindings(inspection, scan),
    ...configurationFindings(scan),
  ], scan.limits.maxFindings));

  return buildResult({
    checkedAt,
    mode: url ? "repo_plus_url" : "repo_only",
    repoPath: inspection.path,
    url,
    inspection,
    findings,
    scan,
    audit,
  });
}

export function classifyGeneratedSiteSmellsError(error: unknown): CliErrorCode {
  if (error instanceof GeneratedSiteSmellsError) return error.code;
  const message = error instanceof Error ? error.message : "";
  if (message.startsWith("Invalid URL")) return "invalid_url";
  if (message.startsWith("Repository path")) return "invalid_repo_path";
  if (/timed out|timeout/i.test(message)) return "timeout";
  if (/fetch|network|getaddrinfo|enotfound|econnrefused|ECONNREFUSED|ENOTFOUND/i.test(message)) return "network_error";
  return "internal_error";
}

function buildResult(input: {
  checkedAt: string;
  mode: "repo_only" | "repo_plus_url";
  repoPath: string;
  url?: string;
  inspection: RepoInspectionResult;
  findings: Finding[];
  scan: RepoSmellScan;
  audit?: AuditResult;
}): GeneratedSiteSmellsJsonContract {
  const severityCounts = countSeverities(input.findings);
  const limitations = unique([
    "Findings are heuristic implementation signals, not proof of who or what produced a site.",
    "This read-only detector reports review targets and does not apply fixes.",
    "The scanner reads only bounded source/config/public text files and skips dependencies, build output, lockfiles, binary files, large media, and environment files.",
    input.mode === "repo_plus_url"
      ? "URL mode reuses ShipReady's existing single-page audit evidence; it is not a multi-page crawl."
      : "Repo-only mode does not verify the live deployed page.",
    ...(input.audit ? [] : ["No live URL evidence was provided for raw-versus-rendered cross-checks."]),
    ...input.scan.limitations,
  ]);

  return GeneratedSiteSmellsJsonContractSchema.parse({
    contract: CONTRACT_NAMES.generatedSiteSmells,
    checkedAt: input.checkedAt,
    mode: input.mode,
    repoPath: input.repoPath,
    ...(input.url ? { url: input.url } : {}),
    framework: {
      kind: input.inspection.framework.id,
      name: input.inspection.framework.name,
      confidence: input.inspection.framework.confidence,
      evidence: input.inspection.framework.evidence,
    },
    summary: {
      status: summaryStatus(input.findings, input.scan),
      severityCounts,
      findingCount: input.findings.length,
    },
    findings: input.findings,
    scanned: {
      files: input.scan.scannedFiles,
      bytes: input.scan.scannedBytes,
      skippedFiles: input.scan.skippedFiles,
      truncated: input.scan.truncated,
      limits: {
        maxFiles: input.scan.limits.maxFiles,
        maxBytes: input.scan.limits.maxBytes,
        maxFileBytes: input.scan.limits.maxFileBytes,
        maxFindings: input.scan.limits.maxFindings,
        maxValuePreviewLength: input.scan.limits.maxValuePreviewLength,
      },
    },
    limitations,
    nextActions: nextActionsFor(input.findings),
  });
}

function frameworkFindings(
  inspection: RepoInspectionResult,
  scan: RepoSmellScan,
): Finding[] {
  const findings: Finding[] = [];
  if (inspection.framework.id === "unknown") {
    findings.push(finding({
      id: "framework.unsupported_shape",
      title: "Project shape needs manual framework review",
      category: "framework",
      severity: "low",
      confidence: "high",
      status: "manual_review",
      evidence: inspection.framework.evidence.slice(0, 3).map((item) => ({
        source: "repo",
        ...(item.path ? { path: item.path } : {}),
        valuePreview: sanitizeValuePreview(item.value),
        message: item.value,
      })),
      whyItMatters: "Unsupported or unclear project shapes make metadata, routing, crawl-file, and public asset conventions harder to evaluate automatically.",
      nextAction: "Manually identify the framework and confirm where raw metadata, crawl files, and public assets are produced.",
      relatedCommands: ["pnpm shipready inspect-repo <path> --json"],
      relatedContracts: [CONTRACT_NAMES.repoInspection, CONTRACT_NAMES.generatedSiteSmells],
    }));
  } else if (inspection.framework.confidence === "low") {
    findings.push(finding({
      id: "framework.low_confidence_detection",
      title: "Framework detection confidence is low",
      category: "framework",
      severity: "low",
      confidence: "medium",
      status: "manual_review",
      evidence: [{ source: "repo", message: `Detected ${inspection.framework.name} with low confidence.` }],
      whyItMatters: "Framework-specific metadata and public asset conventions may be wrong when detection confidence is low.",
      nextAction: "Review the detected framework before acting on metadata, routing, or crawlability recommendations.",
    }));
  }

  const ambiguousWarning = inspection.warnings.find((warning) => /ambiguous/i.test(warning));
  if (ambiguousWarning) {
    findings.push(finding({
      id: "framework.ambiguous_signals",
      title: "Framework signals are ambiguous",
      category: "framework",
      severity: "low",
      confidence: "high",
      status: "manual_review",
      evidence: [{ source: "repo", valuePreview: sanitizeValuePreview(ambiguousWarning), message: "Repo inspection reported ambiguous framework signals." }],
      whyItMatters: "Ambiguous framework shape can hide the actual raw metadata and crawl-file output path.",
      nextAction: "Review the app roots and build output conventions before planning launch-readiness changes.",
    }));
  }

  const appRoots = ["app", "src/app", "pages", "src/pages"].filter((path) => hasRepoDirectory(scan, path));
  if (appRoots.length > 1) {
    findings.push(finding({
      id: "framework.multiple_app_roots",
      title: "Multiple app roots may make routing conventions unclear",
      category: "framework",
      severity: "low",
      confidence: "medium",
      status: "manual_review",
      evidence: appRoots.slice(0, 4).map((path) => ({
        source: "repo",
        path,
        message: `Found app root ${path}.`,
      })),
      whyItMatters: "Multiple app roots can make it unclear which files produce raw metadata, routes, and public crawl resources.",
      nextAction: "Confirm the active app root before moving metadata or crawl-file logic.",
    }));
  }

  const metadataPaths = scan.files
    .filter((file) => isSourceLikeFile(file) && METADATA_SOURCE_PATTERN.test(file.content))
    .map((file) => file.path);
  const metadataDirs = new Set(metadataPaths.map((path) => path.split("/").slice(0, -1).join("/") || "."));
  if (metadataDirs.size >= 4) {
    findings.push(finding({
      id: "framework.metadata_split_across_files",
      title: "Metadata logic appears split across several areas",
      category: "framework",
      severity: "low",
      confidence: "low",
      status: "manual_review",
      evidence: metadataPaths.slice(0, 5).map((path) => ({ source: "scanner", path, message: "Metadata-related pattern found." })),
      whyItMatters: "Split metadata logic can make generated-site launch fixes fragile because raw HTML, route metadata, and preview fields may diverge.",
      nextAction: "Review the active metadata source of truth before changing titles, descriptions, canonicals, or social image fields.",
    }));
  }

  return findings;
}

function crawlabilityFindings(
  inspection: RepoInspectionResult,
  scan: RepoSmellScan,
): Finding[] {
  const expected = expectedCrawlFiles(inspection, scan);
  const missing = expected.filter((item) => !hasRepoFile(scan, item.path));
  const findings: Finding[] = [];
  for (const item of missing) {
    findings.push(finding({
      id: `crawlability.${item.kind}_missing`,
      title: `${item.label} file is not present in the expected location`,
      category: "crawlability",
      severity: "medium",
      confidence: "medium",
      status: "needs_attention",
      evidence: [{ source: "repo", path: item.path, message: `${item.path} was expected for ${inspection.framework.name} but was not found.` }],
      whyItMatters: "Generated sites often omit crawl resources; missing conventional files can make launch-readiness review and crawler discovery less clear.",
      nextAction: "Use `pnpm shipready plan-fixes <path> --url <url> --json` to see whether this is eligible for a guarded crawl-file preview.",
      relatedCommands: ["pnpm shipready plan-fixes <path> --url <url> --json", "pnpm shipready fix <path> --url <url> --dry-run --json"],
      relatedContracts: [CONTRACT_NAMES.fixPlan, CONTRACT_NAMES.dryRunFix, CONTRACT_NAMES.generatedSiteSmells],
    }));
  }

  const expectedPaths = new Set(expected.map((item) => item.path));
  const unusual = scan.snapshot.fileList.filter((path) =>
    /(^|\/)(robots\.txt|sitemap\.xml)$/.test(path) && !expectedPaths.has(path));
  if (unusual.length > 0 && expected.length > 0) {
    findings.push(finding({
      id: "crawlability.unusual_crawl_file_location",
      title: "Crawl file exists outside the expected public location",
      category: "crawlability",
      severity: "low",
      confidence: "medium",
      status: "manual_review",
      evidence: unusual.slice(0, 4).map((path) => ({ source: "repo", path, message: "Crawl resource found in an unusual location." })),
      whyItMatters: "A robots or sitemap file outside the framework's public output path may not ship with the deployed site.",
      nextAction: "Confirm whether the framework copies this file to the public root during build.",
    }));
  }

  return findings;
}

function metadataFindings(
  inspection: RepoInspectionResult,
  scan: RepoSmellScan,
  audit: AuditResult | undefined,
  socialPreview: SocialPreviewJsonContract | undefined,
): Finding[] {
  const findings: Finding[] = [];
  const html = htmlMetadata(scan);
  const weakIndex = html.find((item) => item.path === "index.html" && isWeakHtmlFallback(item));
  const sourceMetadata = findLineEvidence(scan, METADATA_SOURCE_PATTERN, {
    max: scan.limits.maxEvidencePerFinding,
    filePredicate: (file) => isSourceLikeFile(file),
  });

  if (inspection.framework.id === "vite_react" && weakIndex && sourceMetadata.length > 0) {
    findings.push(finding({
      id: "metadata.client_only_metadata",
      title: "Metadata appears to rely on client-side code",
      category: "metadata",
      severity: "high",
      confidence: "medium",
      status: "needs_attention",
      evidence: [
        htmlEvidence(weakIndex, "Raw HTML fallback has weak metadata."),
        ...toEvidence(sourceMetadata.slice(0, 3), "scanner"),
      ],
      whyItMatters: "Preview bots and crawlers often read raw HTML first; metadata injected only after JavaScript runs can be missed.",
      nextAction: "Move essential title, description, canonical, and social image metadata into `index.html` or a server/prerendered metadata surface.",
    }));
  }

  if (inspection.framework.id === "vite_react" && weakIndex) {
    findings.push(finding({
      id: "routing.spa_weak_raw_html",
      title: "SPA fallback looks weak for crawler and preview inputs",
      category: "routing",
      severity: "medium",
      confidence: "medium",
      status: "needs_attention",
      evidence: [htmlEvidence(weakIndex, "The raw SPA shell has generic or missing metadata.")],
      whyItMatters: "Generated-looking SPA shells with weak raw HTML can make crawler and preview-bot inputs fragile.",
      nextAction: "Review whether the app needs stronger raw HTML metadata, prerendering, or a framework path that exposes metadata without client JavaScript.",
    }));
  }

  const genericHtml = html.filter((item) => isGenericMetadata(item.title) || isGenericDescription(item.description));
  if (genericHtml.length > 0) {
    findings.push(finding({
      id: "metadata.generic_title_or_description",
      title: "Title or description is overly generic",
      category: "metadata",
      severity: "low",
      confidence: "medium",
      status: "manual_review",
      evidence: genericHtml.slice(0, 4).map((item) => htmlEvidence(item, "Generic metadata found in raw HTML.")),
      whyItMatters: "Generic metadata commonly appears in starter or generated sites and can make previews unclear.",
      nextAction: "Replace generic title and description values with concise, accurate page-specific metadata.",
    }));
  }

  const duplicatePlaceholder = duplicatePlaceholderMetadata(html);
  if (duplicatePlaceholder.length > 0) {
    findings.push(finding({
      id: "metadata.duplicate_placeholder_branding",
      title: "Placeholder branding repeats across metadata fields",
      category: "metadata",
      severity: "low",
      confidence: "medium",
      status: "manual_review",
      evidence: duplicatePlaceholder.slice(0, 4),
      whyItMatters: "Repeated placeholder branding across document and social metadata suggests launch metadata may not have been reviewed.",
      nextAction: "Review title, Open Graph, Twitter, and site-name fields together for a consistent public brand.",
    }));
  }

  if (audit) {
    const renderedOnly = audit.comparison.fields.filter((field) =>
      field.status === "present_after_render_only" &&
      /title|description|canonical|og:|twitter:/i.test(field.field));
    if (renderedOnly.length > 0) {
      findings.push(finding({
        id: "metadata.rendered_only_metadata",
        title: "Live metadata appears only after rendering",
        category: "metadata",
        severity: "high",
        confidence: "high",
        status: "needs_attention",
        evidence: renderedOnly.slice(0, 5).map((field) => ({
          source: "audit",
          field: field.field,
          valuePreview: sanitizeValuePreview(field.renderedValue),
          message: `${field.field} was absent in raw HTML and present after rendering.`,
        })),
        whyItMatters: "Raw HTML is usually safer for crawler and preview-bot visibility than metadata injected after JavaScript runs.",
        nextAction: "Move essential metadata into raw HTML or the framework's server-rendered metadata path.",
        relatedCommands: ["pnpm shipready audit <url> --json", "pnpm shipready social-preview --url <url> --json"],
        relatedContracts: [CONTRACT_NAMES.audit, CONTRACT_NAMES.socialPreview, CONTRACT_NAMES.generatedSiteSmells],
      }));
    }

    const changedGeneric = audit.comparison.fields.filter((field) =>
      field.status === "changed_after_render" &&
      /title|description/i.test(field.field) &&
      (isGenericMetadata(field.rawValue) || isGenericDescription(field.rawValue)));
    if (changedGeneric.length > 0) {
      findings.push(finding({
        id: "metadata.raw_generic_rendered_differs",
        title: "Raw HTML metadata is generic while rendered metadata differs",
        category: "preview",
        severity: "medium",
        confidence: "high",
        status: "needs_attention",
        evidence: changedGeneric.slice(0, 4).map((field) => ({
          source: "audit",
          field: field.field,
          valuePreview: sanitizeValuePreview(field.rawValue),
          message: `${field.field} has a generic raw value and a different rendered value.`,
        })),
        whyItMatters: "Preview and crawler consumers that do not execute JavaScript may see the generic fallback instead of the rendered value.",
        nextAction: "Update the raw metadata fallback to match the intended rendered launch metadata.",
        relatedCommands: ["pnpm shipready audit <url> --json", "pnpm shipready social-preview --url <url> --json"],
        relatedContracts: [CONTRACT_NAMES.audit, CONTRACT_NAMES.socialPreview, CONTRACT_NAMES.generatedSiteSmells],
      }));
    }
  }

  const renderedPreviewWarnings = socialPreview?.warnings.filter((warning) =>
    /appears only after rendering|rendered HTML/i.test(warning));
  if (renderedPreviewWarnings && renderedPreviewWarnings.length > 0) {
    findings.push(finding({
      id: "preview.rendered_only_inputs",
      title: "Simulated preview inputs rely on rendered metadata",
      category: "preview",
      severity: "medium",
      confidence: "medium",
      status: "needs_attention",
      evidence: renderedPreviewWarnings.slice(0, 4).map((warning) => ({
        source: "social_preview",
        valuePreview: sanitizeValuePreview(warning),
        message: "Social preview simulator reported rendered-only metadata input.",
      })),
      whyItMatters: "Some preview consumers use raw HTML inputs; rendered-only values can make share cards inconsistent.",
      nextAction: "Prefer raw HTML or server-rendered metadata for important social preview fields.",
      relatedCommands: ["pnpm shipready social-preview --url <url> --json"],
      relatedContracts: [CONTRACT_NAMES.socialPreview, CONTRACT_NAMES.generatedSiteSmells],
    }));
  }

  return findings;
}

function placeholderFindings(scan: RepoSmellScan): Finding[] {
  const findings: Finding[] = [];
  const placeholders = findLineEvidence(scan, PLACEHOLDER_PATTERN, {
    max: scan.limits.maxEvidencePerFinding,
  });
  if (placeholders.length > 0) {
    findings.push(finding({
      id: "content.placeholder_copy",
      title: "Placeholder copy remains in scanned files",
      category: "content_placeholders",
      severity: "medium",
      confidence: "high",
      status: "manual_review",
      evidence: toEvidence(placeholders, "repo"),
      whyItMatters: "Placeholder wording commonly appears in generated sites and may make launch metadata, previews, and visible content incomplete.",
      nextAction: "Review the referenced copy and replace placeholders with accurate product language.",
    }));
  }

  const boilerplate = findLineEvidence(scan, BOILERPLATE_PATTERN, {
    max: scan.limits.maxEvidencePerFinding,
  });
  if (boilerplate.length > 0) {
    findings.push(finding({
      id: "generated_boilerplate.default_starter",
      title: "Default starter boilerplate is still present",
      category: "generated_boilerplate",
      severity: "low",
      confidence: "high",
      status: "manual_review",
      evidence: toEvidence(boilerplate, "repo"),
      whyItMatters: "Starter defaults can indicate that launch-critical metadata, branding, and assets were not reviewed after scaffolding.",
      nextAction: "Remove starter text, default logos, and starter assets that are not part of the intended brand.",
    }));
  }

  const generatedMarkers = findLineEvidence(scan, GENERATED_MARKER_PATTERN, {
    max: scan.limits.maxEvidencePerFinding,
    filePredicate: (file) => isSourceLikeFile(file) || file.extension === ".html",
  });
  if (generatedMarkers.length > 0) {
    findings.push(finding({
      id: "generated_boilerplate.generated_code_marker",
      title: "Generated-code marker appears near launch-relevant files",
      category: "generated_boilerplate",
      severity: "info",
      confidence: "medium",
      status: "manual_review",
      evidence: toEvidence(generatedMarkers, "scanner"),
      whyItMatters: "Generated-code markers can cause teams to avoid files that still contain review-required metadata, routing, or asset references.",
      nextAction: "Review the marked files before changing launch metadata or assets; do not assume the marker proves authorship or quality.",
    }));
  }

  return findings;
}

function assetFindings(
  inspection: RepoInspectionResult,
  scan: RepoSmellScan,
): Finding[] {
  const html = htmlMetadata(scan);
  const staticRoot = inspection.framework.id === "static_html";
  const missingSocial: Evidence[] = [];
  const missingFavicons: Evidence[] = [];

  for (const item of html) {
    for (const image of item.socialImages) {
      if (isLocalPublicPath(image.value) && !assetExistsForPublicPath(scan, image.value, staticRoot)) {
        missingSocial.push({
          source: "repo",
          path: item.path,
          ...(image.line ? { line: image.line } : {}),
          field: image.field,
          valuePreview: sanitizeValuePreview(image.value),
          message: `Referenced local social image ${image.value} was not found in the public asset root.`,
        });
      }
    }
    for (const favicon of item.favicons) {
      if (isLocalPublicPath(favicon.value) && !assetExistsForPublicPath(scan, favicon.value, staticRoot)) {
        missingFavicons.push({
          source: "repo",
          path: item.path,
          ...(favicon.line ? { line: favicon.line } : {}),
          field: "favicon",
          valuePreview: sanitizeValuePreview(favicon.value),
          message: `Referenced favicon ${favicon.value} was not found in the public asset root.`,
        });
      }
    }
  }

  const sourceAssetReferences = sourceAssetReferencesNearMetadata(scan);
  for (const reference of sourceAssetReferences) {
    if (!assetExistsForPublicPath(scan, reference.publicPath, staticRoot)) {
      const evidence: Evidence = {
        source: "scanner",
        path: reference.path,
        line: reference.line,
        field: reference.kind,
        valuePreview: sanitizeValuePreview(reference.publicPath),
        message: `Referenced local ${reference.kind} asset ${reference.publicPath} was not found in the public asset root.`,
      };
      if (reference.kind === "social image") {
        missingSocial.push(evidence);
      } else {
        missingFavicons.push(evidence);
      }
    }
  }

  const findings: Finding[] = [];
  if (missingSocial.length > 0) {
    findings.push(finding({
      id: "assets.missing_social_image",
      title: "Referenced social image is missing locally",
      category: "assets",
      severity: "high",
      confidence: "high",
      status: "needs_attention",
      evidence: uniqueEvidence(missingSocial).slice(0, scan.limits.maxEvidencePerFinding),
      whyItMatters: "A missing social image can make shared links fall back to a plain or inconsistent preview.",
      nextAction: "Add the referenced public image or update metadata to an existing launch-ready asset.",
    }));
  }
  if (missingFavicons.length > 0) {
    findings.push(finding({
      id: "assets.missing_favicon",
      title: "Referenced favicon is missing locally",
      category: "assets",
      severity: "low",
      confidence: "high",
      status: "needs_attention",
      evidence: uniqueEvidence(missingFavicons).slice(0, scan.limits.maxEvidencePerFinding),
      whyItMatters: "Missing favicon assets are small launch-readiness issues that can make browser and share surfaces look unfinished.",
      nextAction: "Add the referenced icon under the public asset root or update the favicon link.",
    }));
  }

  return findings;
}

function configurationFindings(scan: RepoSmellScan): Finding[] {
  const findings: Finding[] = [];
  const hardcodedUrls = findLineEvidence(scan, HARDCODED_URL_PATTERN, {
    max: scan.limits.maxEvidencePerFinding,
    filePredicate: (file) => file.extension !== ".md" && isMetadataOrConfigPath(file.path),
  });
  if (hardcodedUrls.length > 0) {
    findings.push(finding({
      id: "configuration.placeholder_or_local_url",
      title: "Metadata or configuration contains a placeholder/local URL",
      category: "configuration",
      severity: "medium",
      confidence: "high",
      status: "needs_attention",
      evidence: toEvidence(hardcodedUrls, "repo"),
      whyItMatters: "Local or placeholder URLs in launch metadata can leak into canonical URLs, sitemaps, and share previews.",
      nextAction: "Replace local and example domains with the intended public origin before deployment.",
    }));
  }

  const absoluteLocalPaths = findLineEvidence(scan, /(["'])(?:file:\/\/\/|\/Users\/|\/home\/)[^"']+\1/i, {
    max: scan.limits.maxEvidencePerFinding,
    filePredicate: (file) => file.extension !== ".md" && isMetadataOrConfigPath(file.path),
  });
  if (absoluteLocalPaths.length > 0) {
    findings.push(finding({
      id: "configuration.absolute_local_path",
      title: "Metadata or configuration references an absolute local path",
      category: "configuration",
      severity: "medium",
      confidence: "high",
      status: "needs_attention",
      evidence: toEvidence(absoluteLocalPaths, "repo"),
      whyItMatters: "Absolute local paths do not work for public crawler, preview, or asset consumers.",
      nextAction: "Replace local filesystem paths with public URLs or public asset paths.",
    }));
  }

  return findings;
}

function htmlMetadata(scan: RepoSmellScan): HtmlMetadata[] {
  return scan.files.filter(isHtmlFile).slice(0, 20).map((file) => {
    const $ = load(file.content);
    const title = clean($("title").first().text());
    const description = clean($("meta[name='description' i]").first().attr("content"));
    const socialImages: HtmlMetadata["socialImages"] = [];
    const favicons: HtmlMetadata["favicons"] = [];
    let hasOpenGraph = false;

    $("meta").each((_, element) => {
      const property = clean($(element).attr("property"))?.toLowerCase();
      const name = clean($(element).attr("name"))?.toLowerCase();
      const key = property ?? name;
      if (key?.startsWith("og:")) hasOpenGraph = true;
      if (key === "og:image" || key === "twitter:image") {
        const value = clean($(element).attr("content"));
        if (value) socialImages.push({ field: key, value, line: lineForValue(file.content, value) });
      }
    });

    $("link").each((_, element) => {
      const rel = clean($(element).attr("rel"))?.toLowerCase() ?? "";
      const href = clean($(element).attr("href"));
      if (!href) return;
      if (rel.split(/\s+/).includes("icon") || rel.includes("shortcut icon") || rel.includes("apple-touch-icon")) {
        favicons.push({ value: href, line: lineForValue(file.content, href) });
      }
    });

    return { path: file.path, title, description, socialImages, favicons, hasOpenGraph };
  });
}

function duplicatePlaceholderMetadata(items: HtmlMetadata[]): Evidence[] {
  const evidence: Evidence[] = [];
  for (const item of items) {
    const values = [
      item.title,
      item.description,
      ...item.socialImages.map((image) => image.value),
    ].filter((value) => value && !isAssetLikeValue(value));
    const placeholderValues = values.filter((value) =>
      isGenericMetadata(value) || isGenericDescription(value) || PLACEHOLDER_PATTERN.test(value ?? ""));
    if (placeholderValues.length >= 2) {
      evidence.push({
        source: "repo",
        path: item.path,
        valuePreview: sanitizeValuePreview(placeholderValues.join(" | ")),
        message: "Multiple placeholder-like metadata values were found in the same HTML file.",
      });
    }
  }
  return evidence;
}

function isAssetLikeValue(value: string): boolean {
  return value.startsWith("/") || /^https?:\/\//i.test(value) || /\.(png|jpe?g|webp|gif|svg|ico)$/i.test(value);
}

function sourceAssetReferencesNearMetadata(scan: RepoSmellScan): Array<{
  path: string;
  line: number;
  publicPath: string;
  kind: "social image" | "favicon";
}> {
  const references: Array<{ path: string; line: number; publicPath: string; kind: "social image" | "favicon" }> = [];
  for (const file of scan.files) {
    if (!isSourceLikeFile(file)) continue;
    const lines = file.content.split(/\r?\n/);
    for (let index = 0; index < lines.length; index += 1) {
      const line = lines[index] ?? "";
      if (!/(og:image|twitter:image|openGraph|twitter|images?\s*:|favicon|icons?\s*:)/i.test(line)) {
        continue;
      }
      for (const match of line.matchAll(LOCAL_ASSET_PATTERN)) {
        const value = match[1];
        if (!value) continue;
        references.push({
          path: file.path,
          line: index + 1,
          publicPath: value,
          kind: /favicon|icons?/i.test(line) || /\.ico$/i.test(value) ? "favicon" : "social image",
        });
      }
    }
  }
  return references.slice(0, scan.limits.maxEvidencePerFinding * 2);
}

function expectedCrawlFiles(
  inspection: RepoInspectionResult,
  scan: RepoSmellScan,
): Array<{ kind: "robots" | "sitemap"; label: string; path: string }> {
  if (inspection.framework.id === "next_app_router") {
    const appDir = hasRepoDirectory(scan, "src/app") ? "src/app" : "app";
    return [
      { kind: "robots", label: "robots", path: `${appDir}/robots.ts` },
      { kind: "sitemap", label: "sitemap", path: `${appDir}/sitemap.ts` },
    ];
  }
  if (["next_pages_router", "vite_react", "astro", "remix"].includes(inspection.framework.id)) {
    return [
      { kind: "robots", label: "robots", path: "public/robots.txt" },
      { kind: "sitemap", label: "sitemap", path: "public/sitemap.xml" },
    ];
  }
  if (inspection.framework.id === "static_html") {
    return [
      { kind: "robots", label: "robots", path: "robots.txt" },
      { kind: "sitemap", label: "sitemap", path: "sitemap.xml" },
    ];
  }
  return [];
}

function isWeakHtmlFallback(item: HtmlMetadata): boolean {
  return (
    !item.title ||
    isGenericMetadata(item.title) ||
    !item.description ||
    isGenericDescription(item.description) ||
    !item.hasOpenGraph
  );
}

function isGenericMetadata(value: string | undefined): boolean {
  const normalized = value?.replace(/\s+/g, " ").trim().toLowerCase();
  if (!normalized) return true;
  return /^(vite \+ react|react app|next app|create next app|untitled|home|website|my website|your website|app|landing page)$/.test(normalized);
}

function isGenericDescription(value: string | undefined): boolean {
  const normalized = value?.replace(/\s+/g, " ").trim().toLowerCase();
  if (!normalized) return true;
  if (normalized.length < 25) return true;
  return /lorem ipsum|todo|change me|replace me|your description|a website|my website|powered by/i.test(normalized);
}

function isLocalPublicPath(value: string): boolean {
  return value.startsWith("/") && !value.startsWith("//");
}

function normalizeSmellUrl(input: string): string {
  const normalized = normalizeAuditUrl(input);
  const parsed = new URL(normalized);
  parsed.search = "";
  parsed.hash = "";
  return parsed.toString();
}

function finding(input: Omit<Finding, "relatedCommands" | "relatedContracts"> & {
  relatedCommands?: string[];
  relatedContracts?: string[];
}): Finding {
  return {
    ...input,
    evidence: input.evidence.slice(0, DEFAULT_GENERATED_SITE_SMELL_LIMITS.maxEvidencePerFinding),
    relatedCommands: input.relatedCommands ?? ["pnpm shipready smells <path> --json"],
    relatedContracts: input.relatedContracts ?? [CONTRACT_NAMES.generatedSiteSmells],
  };
}

function htmlEvidence(item: HtmlMetadata, message: string): Evidence {
  return {
    source: "repo",
    path: item.path,
    valuePreview: sanitizeValuePreview(`title=${item.title ?? "missing"}; description=${item.description ?? "missing"}`),
    message,
  };
}

function toEvidence(items: LineEvidence[], source: Evidence["source"]): Evidence[] {
  return items.map((item) => ({
    source,
    path: item.path,
    line: item.line,
    valuePreview: item.valuePreview,
    message: `${item.path}:${item.line}`,
  }));
}

function lineForValue(content: string, value: string): number | undefined {
  const lines = content.split(/\r?\n/);
  const index = lines.findIndex((line) => line.includes(value));
  return index >= 0 ? index + 1 : undefined;
}

function countSeverities(findings: Finding[]): GeneratedSiteSmellsJsonContract["summary"]["severityCounts"] {
  return findings.reduce((counts, item) => {
    counts[item.severity] += 1;
    return counts;
  }, { high: 0, medium: 0, low: 0, info: 0 });
}

function summaryStatus(
  findings: Finding[],
  scan: RepoSmellScan,
): GeneratedSiteSmellsJsonContract["summary"]["status"] {
  if (scan.scannedFiles === 0) return "unknown";
  if (findings.length === 0) return "clean";
  if (findings.some((item) => item.severity === "high" || item.severity === "medium")) return "needs_attention";
  if (findings.some((item) => item.status === "manual_review")) return "manual_review";
  return "unknown";
}

function nextActionsFor(findings: Finding[]): string[] {
  if (findings.length === 0) {
    return [
      "No generated-site implementation smells were found in the bounded scan; use URL mode if you also want raw-versus-rendered live evidence.",
    ];
  }
  return unique([
    ...findings
      .filter((finding) => finding.severity === "high" || finding.severity === "medium")
      .map((finding) => finding.nextAction),
    "Treat these findings as review targets; they do not prove site authorship or trigger automatic fixes.",
  ]).slice(0, 6);
}

function limitFindings(findings: Finding[], maxFindings: number): Finding[] {
  if (findings.length <= maxFindings) return findings;
  return [
    ...findings.slice(0, maxFindings - 1),
    finding({
      id: "unknown.finding_limit_reached",
      title: "Finding output was capped",
      category: "unknown",
      severity: "info",
      confidence: "high",
      status: "info",
      evidence: [{ source: "scanner", message: `Only the first ${maxFindings} findings are returned.` }],
      whyItMatters: "Capping keeps the read-only output bounded and avoids dumping repository content.",
      nextAction: "Review the top findings first, then rerun with a higher internal cap only if needed.",
      relatedCommands: ["pnpm shipready smells <path> --json"],
      relatedContracts: [CONTRACT_NAMES.generatedSiteSmells],
    }),
  ];
}

function sortFindings(findings: Finding[]): Finding[] {
  const severityRank = { high: 0, medium: 1, low: 2, info: 3 };
  return [...findings].sort((a, b) =>
    severityRank[a.severity] - severityRank[b.severity] ||
    CATEGORY_ORDER.indexOf(a.category) - CATEGORY_ORDER.indexOf(b.category) ||
    a.id.localeCompare(b.id));
}

function uniqueEvidence(evidence: Evidence[]): Evidence[] {
  const seen = new Set<string>();
  return evidence.filter((item) => {
    const key = `${item.path ?? ""}:${item.line ?? ""}:${item.field ?? ""}:${item.valuePreview ?? ""}`;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

function unique(values: string[]): string[] {
  return Array.from(new Set(values.filter(Boolean)));
}

function clean(value: string | undefined): string | undefined {
  const compact = value?.replace(/\s+/g, " ").trim();
  return compact || undefined;
}
